language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge
      cache:
        directories: "$HOME/.composer/cache"
      before_install:
        - wget https://phar.phpunit.de/phpunit-7.1.4.phar
      script:
        - php phpunit-7.1.4.phar --verbose $PHPUNIT_FLAGS

sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
